config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'home/index'
  get 'posts/new'
  get 'search' => 'search#index'

  # halaman utama
  root to: "auth#form_login"

  # register
  get '/daftar', to: 'auth#form_register', as: 'form_register'
  post '/daftar', to: 'auth#register', as: 'register_post'

  # login
  get '/login', to: 'auth#form_login', as: 'form_login'
  post '/login', to: 'auth#login', as: 'login_post'

  # logout
  delete '/logout/:id', to: 'auth#logout', as: 'user_logout'
  
  devise_for :users
  devise_for :accounts
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :show, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
  has_many :post_hash_tags
  has_many :posts, through: :post_hash_tags
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags

  validate :image_presence
  after_commit :create_hash_tags, on: :create

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

    has_secure_password
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # mencari user berdasarkan session key
    def current_user
        if session[:user_id]
            User.find(session[:user_id])
        else
            nil
        end
    end

    # cek apakah user sudah login
    def user_signed_in?
        if current_user
            true
        else
            redirect_to form_login_path, alert: "Silahkan login terlebih dahulu!"
            return false
        end
        
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    def form_register
        
        @user = User.new
    end

    def form_login

    end

    def login
        email = params[:email]
        password = params[:password]
        
        user = User.find_by(email: email)
        if user
            if user.authenticate(password)

                # membuat session dengan key = :user_id
                session[:user_id] = user.id
                redirect_to home_index_path, notice: "Selamat datang #{user.name}"
            else
                redirect_to form_login_path, alert: "Password tidak sesuai"
            end
        else
            redirect_to form_login_path, alert: "email tidak ditemukan"
        end
        
    end

    def register
        @user = User.new(user_params)
        if @user.save

            redirect_to form_login_path, notice: "Berhasil membuat akun!"
        else
            render :form_register
        end
    end

    def logout
        session[:user_id] = nil
        redirect_to form_login_path, notice: "Anda telah logout"
    end

    private
    def user_params
        params.require(:user).permit(:name, :username, :email, :password)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :user_signed_in?
    helper_method :current_user
    
  def index
    @posts = Post.order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end
  
  def create
    Post.create(post_params)
    redirect_to home_index_path
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end

  private
  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def homepage
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name:    query})
    else
      @posts = Post.where("description like ?", "%#{params[:query]}%")
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else  
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def authenticate_user!
    unless current_user
      render 'yourjs'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.save
      redirect_to @user
    else  
      redirect :new
    end
  end

  def show
    @user  = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :website,
                                 :bio, :email, :phone, :gender, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_bookmark_icon.html.erb
<% if is_bookmarked.present? %>
  <%= link_to "Bookmarked", bookmark_path(is_bookmarked), method: :delete, remote: true,
    class: "core-sprite bookmarked hide-text" %>
<% else %>
  <%= link_to "Bookmark", post_bookmarks_path(post), method: :post,
    remote: true, class: "core-sprite bookmark hide-text" %>
<% end %>

app/views/home/_comment_form.html.erb
<%= form_for [post, Comment.new], :html => {:class => "w-100"}, remote: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :post_id, value: post.id %>
  <%= f.text_field :content, class: "form-control comment-input border-0",
     placeholder: "Add a comment ...", autocomplete: :off %>
<% end %>

app/views/home/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "Delete comment", comment_path(comment),
        method: :delete, remote: true, class: "core-sprite delete-comment hide-text" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user),
          class: "no-text-decoration normal-color" %>
      </strong>
    </span>
    <span><%= comment.content %></span>
  </div>
<% end %>

app/views/home/_like_icon.html.erb
<% if is_liked.present? %>
  <%= link_to "Love", like_path(is_liked), method: :delete, remote: true,
    class: "core-sprite loved hide-text" %>
<% else %>
  <%= link_to "Loved", post_likes_path(post), method: :post, remote: true,
    class: "core-sprite love hide-text" %>
<% end %>

app/views/home/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
      <% if likes.size == 1 %>
          <%= like.user.name %> </strong> like this
      <% elsif like == likes.last %>
          </strong>and<strong>
  <%= + like.user.name %></strong> like this
      <% elsif index > 1 %>
          </strong><%= "and " + (likes.size-index).to_s + " others " %> like this
          <% break %>
      <% elsif index==likes.size-2 || index==1%>
          <%= like.user.name %>
      <% else %>
          <%= like.user.name + ", " %>
      <% end %>
  <% end %>
  </strong>

app/views/home/_post.html.erb
<section class="post">
  <div class="user">
    <div class="avatar">
      <% if post.user.avatar.attached? %>
        <%= link_to user_path(post.user) do %>
          <%= image_tag post.user.avatar %>
        <% end %>
      <% end %>
    </div>
    <%= link_to post.user.username, user_path(post.user), class: 'username' %>
  </div>
  <%= image_tag post.image, class: 'main-image' %>
  <div class="description">
    <%= render partial: "posts/description", locals: {post: post} %>
  </div>
</section>

app/views/home/_upload_form.html.erb
<%= form_for Post.new do |f| %>
  <div class="form-group">
    <%= f.text_field :description %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.text_field :user_id, value: current_user.id, class: 'd-none' %>
  </div>
  <br>
  <div class="text-center">
    <%= f.submit 'Create Post', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/home/awal.html.erb
welcome to Instagram Clone

app/views/home/index.html.erb
<div class="homepage row">
<div class="col-md-8">
  <div class='form-upload'>
    <%= render 'history' %>
  </div>

  <div class="posts">
    <% @posts.each do |post| %>
      <%= render partial: 'post', locals: { post: post } %>
    <% end %>
  </div>
  </div>
  <div class="col-md-4">
    <div class='form-upload'>
      
    <b>Asri Nurul</b>
    </div>
    <b> Saran Untuk Anda</b>
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>Tentang.</li>
          <li>Bantuan.</li>
          <li>Pers.</li>
          <li>API.</li>
          <li>Pekerjaan.</li>
          <li>Privasi.</li>
          <li>Ketentuan.</li>
          <li>Lokasi.</li>
          <li>Akun.</li>
          <li>Teratas.</li>
          <li>Tagar.</li>
          <li>Bahasa.</li>
          <li>Indonesia.</li>
        </ul>

        <p> © 2021 INSTAGRAM FROM FACEBOOK </p>
      </nav>
    </footer>
  </div>
</div>

app/views/posts/_description.html.erb
<% post.description.to_s.split(' ').each do |word| %>
  <% if word.start_with?('#') %>
    <%= link_to word, search_path(query: word) %>
  <%else %>
    <%= word %>
  <%end %>
<% end %>

app/views/posts/new.html.erb
<div class="homepage">
  <div class='form-upload'>
    <%= render 'home/upload_form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="post-show row">
  <div class="col-md-8">
    <%=image_tag @post.image, class: 'image' %>
  </div>
  <div class="col-md-4">
    <div class="user">
      <div class="avatar">
        <% if @post.user.avatar.attached? %>
          <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar %>
          <% end %>
        <% end %>
      </div>
      <%= link_to @post.user.username, user_path(@post.user), class: 'username' %>
    </div>
    <div class="description">
      <%= @post.description %>
    </div>
    <div class="delete">
      <% if current_user.posts.exists?(@post.id) %>
        <%= link_to 'Remove', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<div class="search-page">
  <% if @posts.exists? %>
    <h1>Top Posts</h1>
  <% else %>
    <h1>Oop! No matching posts ...</h1>
  <% end %>

  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=link_to post_path(post) do %>
          <%=image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <%= link_to 'Logout', user_logout_path(current_user), method: :delete, class: 'nav-link' %>
      
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: 'avatar' %>
            <%end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%=current_user.username %></p>
            <a class="change-photo" href="">Change Profile Photo</a>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :username, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :website, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_area :bio, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Update", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, placeholder: "Username" %>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Password" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar %>
        <%end %>
      </div>
    </div>
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= @user.username %></h2>
        <% if @user == current_user %>
          <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-outline-dark common-btn edit-profile-btn" %>
          <button type="button" class="core-sprite setting" data-toggle="modal" data-target="#exampleModal"><li class="fa fa-cog"></li></button>
   <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Settings</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="list-group text-center">
              <a href="#" class="list-group-item list-group-item-action">Change Password</a>
              
              <a href="#" class="list-group-item list-group-item-action" data-dismiss="modal">Cancel</a>
            </div>
          </div>
        </div>
      </div>
        <% end %>
      </div>
      <ul class="posts1">
        <li><span><%= @posts.count %></span> posts</li>
        <li><span>195</span> followers</li>
        <li><span>345</span> following</li>
      </ul>
      <h2 class="name"><%=@user.name %></h2>
      <%=link_to @user.website, @user.website, class: 'website' %>
      <%=link_to @user.bio, @user.bio, class: 'bio' %>
    </div>
  </div>

  <div class="user-tabs">
    <a class="tab active" href="">
      <i class="fa fa-th"></i>
      POSTS
    </a>
    <a class="tab" href="">
      <i class="fa fa-tv"></i>
      IGTV
    </a>
    <a class="tab" href="">
      <i class="fa fa-bookmark"></i>
      SAVED
    </a>
    <a class="tab" href="">
      <i class="fa fa-tag"></i>
      TAGGED
    </a>
  </div>

  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=link_to post_path(post) do %>
          <%=image_tag post.image %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>