config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'home/index'
  get 'posts/new'
  get 'search' => 'search#index'

  # halaman utama
  root to: "auth#form_login"

  # register
  get '/daftar', to: 'auth#form_register', as: 'form_register'
  post '/daftar', to: 'auth#register', as: 'register_post'

  # login
  get '/login', to: 'auth#form_login', as: 'form_login'
  post '/login', to: 'auth#login', as: 'login_post'

  # logout
  delete '/logout/:id', to: 'auth#logout', as: 'user_logout'
  
  devise_for :users
  devise_for :accounts
  resources :users, only: [:show, :edit, :update]
  resources :posts, only: [:new, :create, :show, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hash_tag.rb
class HashTag < ApplicationRecord
  has_many :post_hash_tags
  has_many :posts, through: :post_hash_tags
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  has_many :post_hash_tags
  has_many :hash_tags, through: :post_hash_tags

  validate :image_presence
  after_commit :create_hash_tags, on: :create

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name: name)
    end
  end

  def extract_name_hash_tags
    description.to_s.scan(/#\w+/).map{|name| name.gsub("#", "")}
  end
end

app/models/post_hash_tag.rb
class PostHashTag < ApplicationRecord
  belongs_to :post
  belongs_to :hash_tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
    validates :name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

    has_secure_password
  has_one_attached :avatar
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
    def form_register
        
        @user = User.new
    end

    def form_login

    end

    def login
        email = params[:email]
        password = params[:password]
        
        user = User.find_by(email: email)
        if user
            if user.authenticate(password)

                # membuat session dengan key = :user_id
                session[:user_id] = user.id
                redirect_to home_index_path, notice: "Selamat datang #{user.name}"
            else
                redirect_to form_login_path, alert: "Password tidak sesuai"
            end
        else
            redirect_to form_login_path, alert: "email tidak ditemukan"
        end
        
    end

    def register
        @user = User.new(user_params)
        if @user.save

            redirect_to form_login_path, notice: "Berhasil membuat akun!"
        else
            render :form_register
        end
    end

    def logout
        session[:user_id] = nil
        redirect_to form_login_path, notice: "Anda telah logout"
    end

    private
    def user_params
        params.require(:user).permit(:name, :username, :email, :password)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :user_signed_in?
    helper_method :current_user
    
  def index
    @posts = Post.order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end
  
  def create
    Post.create(post_params)
    redirect_to home_index_path
  end
  
  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user)
  end

  private
  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
    def homepage
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].start_with?('#')
      query  = params[:query].gsub('#', '')
      @posts = Post.joins(:hash_tags).where(hash_tags: {name:    query})
    else
      @posts = Post.where("description like ?", "%#{params[:query]}%")
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else  
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]

  def authenticate_user!
    unless current_user
      render 'yourjs'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      @user.save
      redirect_to @user
    else  
      redirect :new
    end
  end

  def show
    @user  = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :website,
                                 :bio, :email, :phone, :gender, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= favicon_link_tag 'icon.png' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%unless current_user.blank? -%>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="#">
             <%= image_tag "ins.png", height: 40 %>
          </a>
        </div>
        <div class="m-auto">
          <%= form_with url: search_path, method: :get, local: true, class: 'form-inline search-form' do |form| %>
            <%= form.text_field :query, value: params[:query], class: 'form-control mr-sm-2', placeholder: '#search' %>
          <% end %>
        </div>
        <div class="user-section">
          <a href="<%= home_index_path %>">
            <i class="fa fa-home"></i>
          </a>
          <a><i class="fa fa-commenting-o"></i></a>
          <a href="<%= posts_new_path %>">
            <i class="fa fa-plus-square-o"></i>
          </a>
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart-o"></i></a>
          <%unless current_user.blank? -%>
            <a href="<%= user_path(current_user)%>">
              <i class="fa fa-user"></i>
            </a>
          <%else -%>
          not signed in
          <%end-%>
        </div>
      </div>
    </nav>
    <%end-%>

    <!--Main content-->
    <main class="container" style="min-height: 550px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2021 INSTAGRAM </p>
      </nav>
    </footer>
  </body>
</html>